#!/data/data/com.termux/files/usr/bin/bash

cp .local/state/mpv/watch_later/616C49357235C475A586182534E42D5E /data/data/com.termux/files/home/storage/shared/Android/media/is.xyz.mpv/watch_later/25A1226C34D95B81856D6E31421CEE2C

am start -a android.intent.action.VIEW -p is.xyz.mpv -t 'audio/*' -d 'file:///storage/emulated/0/Audiobooks/current.m4b'
